-- =========================== 
-- TABELA CLIENTES
-- =========================== 
CREATE TABLE CLIENTES (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    nome VARCHAR2(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    status VARCHAR2(10) DEFAULT 'ativo' CHECK (status IN ('ativo','inativo'))
);


-- =========================== 
-- TABELA APOLICES
-- =========================== 
CREATE TABLE APOLICES (
    id_apolice NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NUMBER NOT NULL,
    id_cliente NUMBER NOT NULL,
    status VARCHAR2(10) DEFAULT 'ativa' CHECK (status IN ('ativa','cancelada','suspensa')),
    valor_segurado NUMBER(10,2) NOT NULL,
    franquia NUMBER(10,2) DEFAULT 0,
    CONSTRAINT fk_apolice_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);


-- =========================== 
-- TABELA SINISTROS
-- =========================== 
CREATE TABLE SINISTROS ( 
    id_sinistro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_apolice NUMBER NOT NULL,
    tipo_sinistro VARCHAR2(50) NOT NULL,
    valor_estimado NUMBER(10,2) NOT NULL,
    status VARCHAR2(15) DEFAULT 'em análise' CHECK (status IN ('em análise','aprovado','recusado','pago')),
    CONSTRAINT fk_sinistro_apolice FOREIGN KEY (id_apolice) REFERENCES APOLICES(id_apolice)
);


-- =========================== 
-- TABELA PAGAMENTOS
-- =========================== 
CREATE TABLE PAGAMENTOS (
    id_pagamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_sinistro NUMBER NOT NULL,
    valor_pago NUMBER(10,2) NOT NULL,
    data_pagamento DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pagamento_sinistro FOREIGN KEY (id_sinistro) REFERENCES SINISTROS(id_sinistro)
);


-- ===========================
-- TABELA HISTORICO_SINISTROS
-- =========================== 
CREATE TABLE HISTORICO_SINISTROS (
    id_historico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    id_cliente NUMBER NOT NULL,
    quantidade_sinistros NUMBER DEFAULT 0,
    data_registro DATE DEFAULT SYSDATE,
    CONSTRAINT fk_historico_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);